name: testing_p1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "run_tests"
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # Install python with required version
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.5"

      # Install libs that app requires
      - name: Install dependencies
        run: python -m pip install -r req.txt

      # Run all pytests and save report to coverage.xml to share it to sonarcloud
      # save report in html format in case that coverall is inavailable
      - name: Run pytests
        run: python -m pytest --cov=roots --cov-report=xml --cov-report=html

      # Load report to coveralls site with a default github token key
      - name: Upload coverage to coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Run SonarCloud with a key that was created in admin panel
      # and added to secrets in repo settings
      - name: Run SonarCloud analysis
        uses: sonarsource/sonarqube-scan-action@v4.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
